name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v2

      - name: 2. setup nodejs...
        uses: actions/setup-node@v2

      - name: 3. install dependencies...
        run: |
          npm install -g yarn
          yarn
      - name: 4. build
        run: |
          yarn build:b
          yarn build:r
          yarn build:v
          yarn build:a
      - name: 5. deploy 'dist files'
        run: |
          mkdir publish
          cd publish
          git init
          git config user.name "XueFLY"
          git config user.email "xuefeng@kcalb.wang"   
          mkdir ng
          mkdir react
          mkdir vue
          cp -r ../packages/screen-recorder-angular/dist/ ./ng/
          cp -r ../packages/screen-recorder-react/dist/ ./react/
          cp -r ../packages/screen-recorder-vue/dist/ ./vue/
          cp ../index.html ./index.html
          cp ../README_PAGES.md ./README.md
          git add .
          git commit -am "Feat: Github Action Auto Build"
          git push --force --quiet https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} master:gh-pages
